/**
 * ReadyDocs Share & Clipboard Utilities
 * Safe sharing without revealing sensitive user data.
 */

export function buildChecklistSummaryText({ checklist, items }) {
  const serviceName = checklist.result_json?.serviceTitle || checklist.institution_name;
  const institution = checklist.institution_name;
  const status = checklist.status === 'ready' 
    ? 'Ready for Visit ✅' 
    : checklist.status === 'needs_attention' 
    ? 'Needs Attention ⚠️' 
    : 'Incomplete ⏳';

  const allItems = items || [];
  const missing = allItems.filter(i => i.status === 'missing' || !i.status);
  const matched = allItems.filter(i => i.status === 'matched');

  let text = `📋 *ReadyDocs Document Checklist*\n`;
  text += `*Service:* ${serviceName}\n`;
  text += `*Institution:* ${institution}\n`;
  text += `*Status:* ${status}\n\n`;

  text += `✅ *Verified Documents (${matched.length}):*\n`;
  if (matched.length > 0) {
    matched.forEach(m => {
      text += `• ${m.title}\n`;
    });
  } else {
    text += `• None yet\n`;
  }
  text += `\n`;

  if (missing.length > 0) {
    text += `❌ *Missing Documents (${missing.length}):*\n`;
    missing.forEach(m => {
      text += `• ${m.title}\n`;
    });
    text += `\n`;
  }

  if (checklist.source_url) {
    text += `🔗 *Official Source:* ${checklist.source_url}\n\n`;
  }

  text += `_Generated by ReadyDocs • "One visit is enough."_`;
  return text;
}

export function shareOnWhatsApp({ checklist, items }) {
  const text = buildChecklistSummaryText({ checklist, items });
  const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

export async function copyChecklistToClipboard({ checklist, items }) {
  const text = buildChecklistSummaryText({ checklist, items });
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
    return false;
  }
}
